"""empty message

Revision ID: 32e4b92fac6e
Revises: 4f635c9a730d
Create Date: 2020-12-19 09:07:48.539053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e4b92fac6e'
down_revision = '4f635c9a730d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('que_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['que_id'], ['question.id'], name='tag_que_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tag_pkey')
    )
    # ### end Alembic commands ###
