"""empty message

Revision ID: 4f635c9a730d
Revises: 72e6f43cf07b
Create Date: 2020-12-18 13:34:24.695733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f635c9a730d'
down_revision = '72e6f43cf07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=True),
    sa.Column('que_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['que_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('question', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('tag')
    # ### end Alembic commands ###
