"""empty message

Revision ID: 72e6f43cf07b
Revises: 0fdc98d92904
Create Date: 2020-12-18 13:15:50.495449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e6f43cf07b'
down_revision = '0fdc98d92904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'tag')
    # ### end Alembic commands ###
